config/routes.rb
Houndapp::Application.routes.draw do
  mount Resque::Server, at: "/queue"

  get "/auth/github/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"
  get "/configuration", to: "application#configuration"

  get "/faq", to: "pages#show", id: "faq"

  resource :account, only: [:show]
  resources :builds, only: [:create]

  resources :repos, only: [:index] do
    resource :activation, only: [:create]
    resource :deactivation, only: [:create]
    resource :subscription, only: [:create, :destroy]
  end

  resources :repo_syncs, only: [:index, :create]
  resource :user, only: [:show]

  root to: "home#index"
end

app/views/shared/_footer.haml
%footer.app-footer
  %p
    Hound is maintained by #{link_to 'thoughtbot', 'http://thoughtbot.com'}.
    Questions? Try the
    #{link_to 'FAQ', faq_path} or
    Tweet #{link_to '@houndci', 'https://twitter.com/houndci'}.

  %p
    Hound is Copyright &copy; #{Date.today.year} thoughtbot. It is open source
    software and may be redistributed under the terms specified in the
    #{link_to 'LICENSE', 'https://github.com/thoughtbot/hound/blob/master/LICENSE'}.

  %ul.links
    %li
      = link_to "Source Code", "https://github.com/thoughtbot/hound"
    %li
      = link_to "FAQ", faq_path
    %li
      = link_to "Terms", "https://github.com/thoughtbot/hound/blob/master/doc/TERMS.md"
    %li
      = link_to "Privacy", "https://github.com/thoughtbot/hound/blob/master/doc/PRIVACY.md"
    %li
      = link_to "Security", "https://github.com/thoughtbot/hound/blob/master/doc/SECURITY.md"

app/views/shared/_header.haml
%header
  = link_to root_path do
    %h1.logo Hound
  - if signed_in?
    %ul.nav
      %li.dropdown
        %input#account-menu-toggle{type: 'checkbox'}
        %label.toggle{for: 'account-menu-toggle'} #{current_user}
        .menu
          = link_to 'Your Repos', repos_path, class: 'repo-link'
          = link_to "Your Account", account_path
          = link_to 'Configure Hound', configuration_path
          = link_to 'FAQ', faq_path
          = link_to 'Sign Out', sign_out_path

app/views/shared/_intercom_settings.haml
:javascript
  window.analytics.identify("#{current_user.id}", {
    created : "#{current_user.created_at}",
    email : "#{current_user.email_address}",
    username : "#{current_user.github_username}"
  }, {
    Intercom : {
      userHash : "#{OpenSSL::HMAC.hexdigest('sha256', ENV['INTERCOM_API_SECRET'], current_user.id.to_s)}"
    }
  });